# .github/workflows/deploy.yml
name: Build and Deploy aljazara.com

on:
  push:
    branches:
      - test-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
        env:
          NEXT_PUBLIC_API_PATH: ${{ secrets.NEXT_PUBLIC_API_PATH }}
          CURRENT_IMPL: ${{ secrets.CURRENT_IMPL }}

      - name: Install dependencies
        run: npm install

      - name: Debug env
        run: printenv | grep NEXT
        env:
          NEXT_PUBLIC_API_PATH: ${{ secrets.NEXT_PUBLIC_API_PATH }}

      # - name: Build SSG
      #   run: npm run build && npm run postbuild
